/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.rl337.metro;


import org.rl337.metro.model.Color;
import org.rl337.metro.model.Point2D;
import org.rl337.metro.model.ThingStack;
import org.rl337.metro.model.shapes.Circle;
import org.rl337.metro.model.things.SimpleThing;
import org.rl337.metro.model.things.Thing;

import java.util.ArrayList;
import java.util.List;

public class App {

    public static void main(String[] args) {

        Renderer renderer = new Renderer(1024, 768);

        List<Thing> thingList = new ArrayList<>();
        for (int x = 0; x < 4; x++) {
            for (int y = 0; y < 4; y++) {

                thingList.add(
                    new SimpleThing(
                        new Circle(new Point2D(10 + 100 * x, 10 + 100 * y), 5),
                        Color.White,
                        0
                    )
                );
            }
        }
        ThingStack shapeList = new ThingStack(thingList);
        renderer.render(shapeList);
        renderer.show();
    }

}
